# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: elastic-search

# Elasticsearch Configuration
elasticInstances: 1                                  # Number of Elasticsearch instances
# elasticVersion: "8.17.0"                           # Optional: Elasticsearch version (defaults to Chart's appVersion)


# Storage Configuration (optional)
# storageSize: "4Gi"                                   # Storage size
# storageClass: "managed-premium"                      # Storage class


# Resource Configuration (optional)
# resources:
#   requests:
#     cpu: "1"
#     memory: "2Gi"
#   limits:
#     cpu: "2"
#     memory: "3Gi"


# Node Configuration (optional)
nodeSelector: "cluster-paas"

# High Availability Configuration (optional)
# 1: Single node (default)
# 2: Two node cluster (not recommended for production)
# 3: Three node HA cluster
# zones: 1

# Azure Configuration (optional)
azure: {}
# azure:
#   configEndpoint: "https://el-config.azconfig.io"  # Azure App Configuration endpoint
#   storageAccountName: "el-snapshots"               # Enable Snapshots by providing a Storage Account name
#   snapshots:
#     containerName: "snapshots"                     # Storage AccountContainer name
