# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: elastic-search

azure:
  configEndpoint: "https://el-config.azconfig.io"
  snapshots:
    storageAccountName: "el-snapshots"
    containerName: "snapshots"

elasticInstances: 1
elasticVersion: "8.17.0"
# storageSize: "4Gi"
# storageClass: "managed-premium"
resiliency: true

# Resource limits and requests
resources: {}
  # requests:
  #   cpu: "2"
  #   memory: "4Gi"
  # limits:
  #   cpu: "4"
  #   memory: "8Gi"

