---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: azure-keyvault-postgresql
  namespace: default
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  targetNamespace: postgresql
  releaseName: keyvault-secrets
  chart:
    spec:
      chart: ./charts/keyvault-secrets
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: system-values
      valuesKey: values.yaml
  values:
    identity: true
    secrets:
      - secretName: postgresql-user-credentials
        data:
          - key: username
            vaultSecret: cpng-user-name
            iterate: true
          - key: password
            vaultSecret: cpng-user-password
            iterate: true
      - secretName: postgresql-superuser-credentials
        data:
          - key: username
            vaultSecret: cpng-superuser-name
            iterate: true
          - key: password
            vaultSecret: cpng-superuser-password
            iterate: true