{{- $elasticInstances := .Values.elasticInstances | default 1 | int }}
{{- range $i := until $elasticInstances }}
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-{{ $i }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    eck.k8s.elastic.co/downward-node-labels: "topology.kubernetes.io/zone"
spec:
  version: {{ $.Values.elasticVersion }}
  config:
    # Azure Repository Plugin settings
    repository.azure.client.default.account: {{ $.Values.azure.storageAccountName }}
    repository.azure.client.default.auth: "MSI"
    repository.azure.token_file: "/var/run/secrets/azure/tokens/azure-identity-token"
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        type: ClusterIP
  nodeSets:
    - name: default
      count: 1
      plugins:
        - repository-azure
      config:
        # Disable memory mapping to avoid vm.max_map_count bootstrap check
        node.store.allow_mmap: false
        node.attr.zone: "${ZONE}"
        cluster.routing.allocation.awareness.attributes: k8s_node_name,zone
      podTemplate:
        metadata:
          labels:
            azure.workload.identity/use: "true"
        spec:
          serviceAccountName: workload-identity-sa
          containers:
            - name: elasticsearch
              env:
                - name: AZURE_FEDERATED_TOKEN_FILE
                  value: /var/run/secrets/azure/tokens/azure-identity-token
          tolerations:
            - effect: NoSchedule
              key: app
              value: "cluster"
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: agentpool
                        operator: In
                        values:
                          - z1pool
                          - z2pool
                          - z3pool
                  - matchExpressions:
                      - key: topology.kubernetes.io/zone
                        operator: In
                        values:
                          - "$(ZONE)-1"
                          - "$(ZONE)-2"
                          - "$(ZONE)-3"
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: topology.kubernetes.io/zone
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
                  elasticsearch.k8s.elastic.co/statefulset-name: elasticsearch-es-default
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: {{ $.Values.storageSize }}
            storageClassName: {{ $.Values.storageClass | default "managed-premium" }}
{{- end }}