{{- $elasticInstances := .Values.elasticInstances | default 1 | int }}
{{- range $i := until $elasticInstances }}
{{- if not $.Values.azure }}
---
apiVersion: v1
kind: Secret
metadata:
  name: kibana-{{ $i }}-service-account
  namespace: {{ $.Release.Namespace }}
  annotations:
    elastic.co/service-account: "true"
type: Opaque
data: {}
{{- end }}
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-{{ $i }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    kibana.k8s.elastic.co/skip-auth-config: "true" # Disable service account auth.
spec:
  version: {{ $.Values.elasticVersion }}
  {{- if not $.Values.azure }}
  elasticsearchRef:
    name: elasticsearch-{{ $i }}
  {{- end }}
  config:
    elasticsearch.hosts: ["http://elasticsearch-{{ $i }}-es-http.{{ $.Release.Namespace }}.svc.cluster.local:9200"]
    {{- if $.Values.azure }}
    elasticsearch.username: "${ELASTICSEARCH_USERNAME}"
    elasticsearch.password: "${ELASTICSEARCH_PASSWORD}"
    xpack.encryptedSavedObjects.encryptionKey: "${XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY}"
    {{- end }}
  count: 1
  podTemplate:
    spec:
      {{- if $.Values.nodeSelector }}
      {{- if $.Values.nodeSelector.toleration }}
      tolerations:
      - effect: NoSchedule
        key: app
        value: {{ $.Values.nodeSelector.toleration }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - z1pool
                - z2pool
                - z3pool
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - "$(ZONE)-1"
                - "$(ZONE)-2"
                - "$(ZONE)-3"
      {{- end }}
      {{- end }}
      initContainers:
      - name: health-check
        image: mcr.microsoft.com/cbl-mariner/base/core:2.0
        command: ["/bin/sh"]
        args:
        - -c
        - |
          tdnf install -y curl jq && \
          while true; do
            health_status=$(curl -u "elastic:$(cat /mnt/elasticsearch-es-elastic-user/elastic)" -k -s "http://elasticsearch-{{ $i }}-es-http.${NAMESPACE}.svc.cluster.local:9200/_cluster/health" | jq -r '.status')
            if [ "$health_status" = "green" ]; then
              echo "Cluster health is green."
              exit 0
            fi
            echo "Cluster health is $health_status. Waiting for it to be green..."
            sleep 30
          done
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: es-basic-auth
          mountPath: /mnt/elasticsearch-es-elastic-user
      containers:
        - name: kibana
          env:
            {{- if $.Values.azure }}
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-credentials
                  key: username-{{ $i }}
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-credentials
                  key: password-{{ $i }}
            - name: XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-credentials
                  key: key-{{ $i }}
            {{- end }}
      volumes:
      - name: es-basic-auth  # Default credentials for elastic.
        secret:
          secretName: elasticsearch-{{ $i }}-es-elastic-user
{{- end }}