{{- range .Values.databases }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .name }}-cluster
  namespace: postgresql
spec:
  inheritedMetadata:
    labels:
      azure.workload.identity/use: "true"

  serviceAccountTemplate:
    metadata:
      annotations:
        azure.workload.identity/client-id: workload-identity-sa
      labels:
        azure.workload.identity/use: "true"

  instances: {{ .instances | default 3 }}
  startDelay: 30
  stopDelay: 30
  minSyncReplicas: 1
  maxSyncReplicas: 1

  replicationSlots:
    highAvailability:
      enabled: true
    updateInterval: 30

  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        cnpg.io/cluster: {{ .name }}-cluster

  affinity:
    tolerations:
    - effect: NoSchedule
      key: app
      value: "cluster"

  {{- if .resources }}
  resources:
    requests:
      {{- if .resources.memory }}
      memory: {{ .resources.memory }}
      {{- end }}
      {{- if .resources.cpu }}
      cpu: {{ .resources.cpu }}
      {{- end }}
    limits:
      {{- if .resources.memory }}
      memory: {{ .resources.memory }}
      {{- end }}
      {{- if .resources.cpu }}
      cpu: {{ .resources.cpu }}
      {{- end }}
  {{- end }}

  bootstrap:
    initdb:
      database: {{ .name }}-db
      owner: dbuser
      secret:
        name: postgresql-user-credentials
      dataChecksums: true

  storage:
    size: 2Gi
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: managed-csi-premium

  walStorage:
    size: 2Gi
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: managed-csi-premium

  # monitoring:
  #   enablePodMonitor: true



  superuserSecret:
    name: postgresql-superuser-credentials

  postgresql:
    pg_hba:
      - host {{ .name }}-db airflow all password
{{- end }}